openapi: 3.0.3
info:
  title: Departments API
  version: 1.0.0
  description: API for departments and employees
paths:
  /api/departments/:
    post:
      operationId: departments_create
      description: Представление создания подразделения.
      tags:
      - departments
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DepartmentCreate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/DepartmentCreate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/DepartmentCreate'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DepartmentCreate'
          description: ''
  /api/departments/{id}/:
    get:
      operationId: departments_retrieve
      description: |-
        Представление для работы с конкретным подразделением.

        GET, PATCH, DELETE.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - departments
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DepartmentTree'
          description: ''
    put:
      operationId: departments_update
      description: |-
        Представление для работы с конкретным подразделением.

        GET, PATCH, DELETE.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - departments
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DepartmentTree'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/DepartmentTree'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/DepartmentTree'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DepartmentTree'
          description: ''
    patch:
      operationId: departments_partial_update
      description: |-
        Представление для работы с конкретным подразделением.

        GET, PATCH, DELETE.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - departments
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedDepartmentUpdate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedDepartmentUpdate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedDepartmentUpdate'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DepartmentUpdate'
          description: ''
    delete:
      operationId: departments_destroy
      description: |-
        Представление для работы с конкретным подразделением.

        GET, PATCH, DELETE.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - departments
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/departments/{id}/employees/:
    post:
      operationId: departments_employees_create
      description: Представление создания сотрудника.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - departments
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmployeeCreate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/EmployeeCreate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/EmployeeCreate'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployeeCreate'
          description: ''
  /api/schema/:
    get:
      operationId: schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - schema
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
components:
  schemas:
    DepartmentCreate:
      type: object
      description: Сериализатор для создания подразделений.
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
        parent_id:
          type: integer
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
          title: Дата создания
      required:
      - created_at
      - id
      - name
      - parent_id
    DepartmentTree:
      type: object
      description: Сериализатор вывода дерева подразделений до заданной глубины.
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          title: Подразделение
          maxLength: 200
        employees:
          type: array
          items:
            type: object
            additionalProperties: {}
          nullable: true
          description: Получает отсортированный список сотрудников.
          readOnly: true
        children:
          type: array
          items:
            type: object
            additionalProperties: {}
          description: Рекурсивно собирает поддерево до указанной глубины depth.
          readOnly: true
      required:
      - children
      - employees
      - id
      - name
    DepartmentUpdate:
      type: object
      description: Сериализатор для обновления подразделений.
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
        parent_id:
          type: integer
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
          title: Дата создания
      required:
      - created_at
      - id
      - name
      - parent_id
    EmployeeCreate:
      type: object
      description: Сериализатор для создания сотрудников.
      properties:
        id:
          type: integer
          readOnly: true
        full_name:
          type: string
        position:
          type: string
        department_id:
          type: integer
          readOnly: true
        hired_at:
          type: string
          format: date
          nullable: true
          title: Дата найма
        created_at:
          type: string
          format: date-time
          readOnly: true
          title: Дата создания
      required:
      - created_at
      - department_id
      - full_name
      - id
      - position
    PatchedDepartmentUpdate:
      type: object
      description: Сериализатор для обновления подразделений.
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
        parent_id:
          type: integer
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
          title: Дата создания
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
